Abstraction
korkoza/java_automation pull request #1
Opened 2021-02-24 20:17 UTC by korkoza

Hello my friend!

Please take a look to the changes

2021-03-02 08:12 UTC, toleksyn requested changes

2021-03-02 08:12 UTC, toleksyn commented on src/lesson1/AbstractAuto.java
> +    public void drive() {
you do not need this

2021-03-02 08:12 UTC, toleksyn commented on src/lesson1/AnotherClass.java
> +        Hybrid car1 = new Hybrid("Toyota", "Prius", 2018, "Electricity, Gas");
variables names should be names specifically

2021-03-02 08:12 UTC, toleksyn commented on src/lesson2/Employee.java
> +    public abstract float averageSalary();
getCalculatedSalary()

2021-03-02 08:12 UTC, toleksyn commented on src/lesson2/EmployeeFixed.java
> +public class EmployeeFixed extends Employee{
FixedSalaryEmployee

2021-03-02 08:12 UTC, toleksyn commented on src/lesson2/EmployeeFixed.java
> +    Float fixedValue;
access modifiers

2021-03-02 08:12 UTC, toleksyn commented on src/lesson2/EmployeeRate.java
> +    float rate;
same

2021-03-02 08:12 UTC, toleksyn commented on src/lesson2/EmployeeRate.java
> +        return (float) (20.8 * 8 * rate);
20.8, 8 -> parameters

2021-03-02 08:12 UTC, toleksyn commented on src/lesson2/ShowInfo.java
> +        EmployeeFixed emp1 = new EmployeeFixed("Jhon", "Doe", "1", 3123.8f);
rename variable names

2021-03-02 08:56 UTC, toleksyn commented on src/lesson2/EmployeeRate.java
> +        return (float) (20.8 * 8 * rate);
getCalculatedSalary(20.8, 8)

2021-03-04 08:43 UTC, korkoza commented on src/lesson1/AbstractAuto.java
> +    public void drive() {
removed the method from abstract class

2021-03-04 08:43 UTC, korkoza commented on src/lesson1/AnotherClass.java
> +        Hybrid car1 = new Hybrid("Toyota", "Prius", 2018, "Electricity, Gas");
variables were renamed

2021-03-04 08:44 UTC, korkoza commented on src/lesson2/Employee.java
> +    public abstract float averageSalary();
renamed the method

2021-03-04 08:44 UTC, korkoza commented on src/lesson2/EmployeeFixed.java
> +public class EmployeeFixed extends Employee{
renamed the class name

2021-03-04 08:45 UTC, korkoza commented on src/lesson2/EmployeeFixed.java
> +    Float fixedValue;
added access modifiers

2021-03-04 08:45 UTC, korkoza commented on src/lesson2/EmployeeRate.java
> +    float rate;
added access modifiers

2021-03-04 08:46 UTC, korkoza commented on src/lesson2/EmployeeRate.java
> +        return (float) (20.8 * 8 * rate);
values are passed as parameters now

2021-03-04 08:46 UTC, korkoza commented on src/lesson2/ShowInfo.java
> +        EmployeeFixed emp1 = new EmployeeFixed("Jhon", "Doe", "1", 3123.8f);
variables were renamed

2021-03-04 08:47 UTC, korkoza commented
Hello again
Please have a look to the changes

2021-03-23 08:14 UTC, merged