Setup IDE to run UI test. Write tests according to given tasks
korkoza/java_automation pull request #4
Opened 2021-04-02 13:03 UTC by korkoza

2021-04-06 05:22 UTC, toleksyn requested changes

2021-04-06 05:22 UTC, toleksyn commented on Lesson1.iml
>  </module>
you can remove these files from git and add to .gitignore

2021-04-06 05:22 UTC, toleksyn commented on src/main/java/JavaPractice/ExceptionPractice.java
> +package JavaPractice;
packages are lower case

2021-04-06 05:22 UTC, toleksyn commented on src/test/java/FirstUITest.java
> +    static WebDriver chromeDriver = new ChromeDriver();
access modifiers

2021-04-06 05:22 UTC, toleksyn commented on src/test/java/FirstUITest.java
> +    }
try not to use static block, move to method

2021-04-06 05:22 UTC, toleksyn commented on src/test/java/FirstUITest.java
> +        chromeDriver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
these are duplicated, so can be moved to before method

2021-04-06 05:22 UTC, toleksyn commented on src/test/java/FirstUITest.java
> +        Assert.assertTrue(firstResult.contains("funny kitten"));
"funny kitten" to variable

2021-04-06 05:22 UTC, toleksyn commented on src/test/java/FirstUITest.java
> +                .findElement(By.xpath("//div[@class='islrc']/div[10]"));
or findElements().size() == 10

2021-04-06 05:22 UTC, toleksyn commented on src/test/java/FirstUITest.java
> +        Assert.assertTrue(firstImageText.contains("Funny")||fifthImageText.contains("Funny"));
Funny  to variable

2021-04-13 05:31 UTC, toleksyn requested changes

2021-04-13 05:31 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +                    .getLinkContainingText(chekedResource);
this should be getLinks(), you'll get a list of links and then verify

2021-04-13 05:31 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +                .goToImages()
toToImagesPage()

2021-04-13 05:31 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +       new GoogleHomePage().open();
you can add a class field and re-use googleHomePage instead of creating anew

2021-04-13 05:31 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +                .clickOnLogo()
no click etc in names

2021-04-13 05:31 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +        Assert.assertTrue(firstImageText.contains(varForAssertion)||fifthImageText.contains(varForAssertion));
spit asserts

2021-04-15 05:32 UTC, toleksyn requested changes

2021-04-15 05:32 UTC, toleksyn commented on .gitignore
> +src/main/java/javaPractice
add build here, here build from git

2021-04-15 05:32 UTC, toleksyn commented on pom.xml
> +            <version>3.141.59</version>
extract to var
same for all

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/Base.java
> +public class Base {
BasePage()

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +    GoogleSearchResultPage googleSearchResultPage = new GoogleSearchResultPage();
access modifiers
no need to create separately

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +                .resultContainsText(verifiedText);
re-do into getSearchResults()

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +        boolean result = googleHomePage
rename

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +        String varForAssertion = "Funny";
rename

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +                .typeTextToSearchField("funny kitten")
setSearchValue() ?

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +        boolean titleContainsText = title.contains(verifiedValue);
all booleans start with is* or are*

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +                .getNumberOfResultsOnPage();
this is more count, amount, quantity than number

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +                .getPageNumberByPosition(2); // 1 is for "Previous", 12 is for "Next"
misleading, deal with this in the method

2021-04-15 05:32 UTC, toleksyn commented on src/test/java/google/GoogleSearchResultPage.java
> +        }
don't do any validation in page objects, just return data and verify data in tests

2021-04-15 07:13 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +       googleHomePage.open();
googleHomePage = new GoogleHomepage().open();

2021-04-15 07:27 UTC, toleksyn commented on src/test/java/google/GoogleSearchResultPage.java
> +    public String getPageNumberByPosition(int position) {
getCurrentPageNumber()

2021-04-15 14:12 UTC, toleksyn requested changes

2021-04-15 14:12 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +        boolean doesResultContainText = false;
declare variables when needed, not before hand
move line 23 to line 34
line 24 to line 29

2021-04-15 14:12 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +        for(String i:results){
code format before commiting
rename i

2021-04-15 14:12 UTC, toleksyn commented on src/test/java/google/FirstUITest.java
> +            if (doesResultContainText) break;
add {} brackets

2021-04-15 14:13 UTC, toleksyn requested changes

2021-04-15 14:13 UTC, toleksyn commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
remove this from git

2021-04-15 14:13 UTC, toleksyn commented on build/reports/tests/1618422006128.0.html
> +<html itemscope="" itemtype="http://schema.org/WebPage" lang="uk"><head><meta charset="UTF-8"><meta content="origin" name="referrer"><meta content="/images/branding/googleg/1x/googleg_standard_color_
remove all these build files from git

2021-04-15 16:34 UTC, korkoza commented on src/test/java/google/FirstUITest.java
> +        for(String i:results){
Could you elaborate on "code format before commiting" please?

2021-04-15 16:48 UTC, korkoza commented on src/test/java/google/FirstUITest.java
> +        boolean doesResultContainText = false;
moved lines to 27-28 because both of them are used in for() block.
one question to the topic. is it normal to separate declaration by empty line?

2021-04-20 05:32 UTC, toleksyn requested changes

2021-04-20 05:32 UTC, toleksyn commented on .gitignore
> +Lesson1.iml
use *.iml

2021-04-20 11:35 UTC, merged