Implemented tests for ordering
korkoza/java_automation pull request #7
Opened 2021-05-10 19:50 UTC by korkoza

2021-05-11 07:14 UTC, toleksyn requested changes

2021-05-11 07:14 UTC, toleksyn commented on src/main/page_objects/CategoryPage.java
> +    public SubCategoryPage openPlantsSubCategory() {
openSubCategory(SubCategoryEnum,PLANTS)

2021-05-11 07:14 UTC, toleksyn commented on src/main/page_objects/CategoryPage.java
> +        $x("//a[@title='Рослини і догляд за ними'][1]")
avoid using Cyrillic in locators

2021-05-11 07:47 UTC, toleksyn commented on src/main/page_objects/SubCategoryPage.java
> +    }
class Product {
    private boolean isTopSale;
    private String name;

}

2021-05-13 07:33 UTC, toleksyn requested changes

2021-05-13 07:33 UTC, toleksyn commented on src/main/page_objects/CategoryPage.java
> +    public SubCategoryPage openSubCategory(SubCategoryEnum locator) {
rename

2021-05-13 07:33 UTC, toleksyn commented on src/main/page_objects/Product.java
> +        }
avoid catching NoSuchElement exs

2021-05-13 07:33 UTC, toleksyn commented on src/main/page_objects/SubCategoryPage.java
> +    public ArrayList<Product> getAllProducts() {
LIst<Product>

2021-05-13 07:33 UTC, toleksyn commented on src/main/page_objects/SubCategoryPage.java
> +        }
can use steam here

2021-05-13 07:33 UTC, toleksyn commented on src/test/java/rozetka/ProductsSortingTest.java
> +        }
just use Ordering.natural().isOrdered

2021-05-13 07:33 UTC, toleksyn commented on src/test/java/rozetka/ProductsSortingTest.java
> +                break;
same

2021-05-13 07:38 UTC, toleksyn commented on src/main/page_objects/Product.java
> +                    "span[contains((@class),'popularity')]", position)).exists();
static void elementExists(element, timeout) {
    try{ 
       return element.should(exist, timeout).exists();
    } catch (AssertionError e) {
       return false; 
    }
}

2021-05-13 07:40 UTC, toleksyn commented on src/main/page_objects/SubCategoryPage.java
> +        }
IntSteam.rangeClosed(1, productsQuantity)
    .mapToObj(number -> new Product(number))
    .collect(toList());

2021-05-13 07:42 UTC, toleksyn commented on src/test/java/rozetka/ProductsSortingTest.java
> +        }
productList
   .stream()
   .map(product -> product.getPrice())
   .collect(toList);

2021-05-13 07:48 UTC, toleksyn commented on src/test/java/rozetka/ProductsSortingTest.java
> +        for (int i = 0; i < productsList.size() - 1; i++) {
productList
.stream()
.map(product -> product.isTopSales())
.map(isTopSale -> isTopSale ? 1 : 0)
.collect(toList); // list with 1 and 0

2021-05-13 13:12 UTC, korkoza commented on src/main/page_objects/Product.java
> +                    "span[contains((@class),'popularity')]", position)).exists();
I still used NoSuchElementException catch as the wait for products loading is made in the getAllProducts() method which is called prior to Product objects creation.

In case of should(exist) usage it would wait for set timeout on each element without label making a test last too long.

Is that fine?

2021-05-18 06:31 UTC, toleksyn requested changes

2021-05-18 06:31 UTC, toleksyn commented on src/main/page_objects/SortingOptionEnum.java
> +public enum SortingOptionEnum {
can drop enum here

2021-05-18 06:31 UTC, toleksyn commented on src/test/java/rozetka/ProductsSortingTest.java
> +        var areProductsSortedByPriceDesc = Ordering.natural().reverse().isOrdered(productPricesList);
new line on chain

2021-05-18 06:31 UTC, toleksyn commented on src/main/util/WebElementUtil.java
> +            return element.exists();
this won't throw no such element (probably)

2021-05-21 14:39 UTC, merged